8주차세미나/Account/urls.py
from django.urls import path
from . import views as views
from django.contrib.auth.views import LogoutView

app_name = "account"

urlpatterns = [
    path("user/create/",views.UserCreate.as_view(), name = "signup"),
    path("user/login/",views.UserLoginView.as_view(),name = "login"),
    path("user/logout/",views.LogoutView.as_view(),name = "logout"),
    path("user/retrieve/",views.UserDetailView.as_view(),name = "user_detail"),
    path("user/update/",views.UserUpdateView.as_view()),
    path("user/delete/",views.UserDeleteView.as_view()),

]

8주차세미나/Post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path('create/', views.PostCreate.as_view(),name = "create"),
    path('list/cbv/', views.PostListView.as_view(),name = "list"),
    path('list/', views.PostListApiView.as_view(),name = "list_api"),
    path('detail/<int:pk>/cbv', views.PostDetailView.as_view(),name = "detail"),
    path('detail/<int:pk>/', views.PostDetailApiView.as_view(),name = "detail_api"),
    path('update/<int:pk>/', views.PostUpdateView.as_view(),name = "update"),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(),name = "delete"),

]

8주차세미나/Singlepage/urls.py
from django.urls import path
from . import views as views

app_name = "single_page"

urlpatterns = [
    path("",views.indexTemplateView.as_view(),name = "main"),
]

8주차세미나/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/",include("Account.urls")),
    path("",include("Singlepage.urls")),
    path("post/",include("Post.urls")),
    path("comment/",include("Comment.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

8주차세미나/Singlepage/models.py
from django.db import models

# Create your models here.

8주차세미나/Singlepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class indexTemplateView(TemplateView):
    template_name = "index.html"

8주차세미나/Singlepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>멋사와 함께 하는 블로그 세미나</title>
    <link rel="stylesheet" href="../static/css/index.css">
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>
    <div class="main_body_wrap">
        <div class="main_height_body_wrap">
            <div class="main_menu">
                <h2 onClick="location.href='/'">BLOG CRUD 연습하기</h2>
                <div class="main_right_menu">
                    {% if user.is_authenticated %}
                    <p class="userName">환영합니다 {{user.get_full_name}}님</p>
                    <button type="button" class="logoutBt" onclick="logout();">로그아웃</button>
                      {% else %}
                        <p onclick="location.href='{% url 'account:login' %}'">로그인</p>
                        <p onclick="location.href='{% url 'account:signup' %}'">회원가입</p>

                      {% endif %}
                </div>
            </div>
            <div class="main_body">
                <div class="main_top_body">
                    <img src="./../static/img/hoon.png"/>
                    <div>
                        <h1>
                            <div class="likelion_p">멋사</div>
                            와 함께 하는<br/>
                            게시판 CRUD 만들기
                        </h1>
                        <button type="button" onclick="location.href='{% url 'post:list' %}'">게시판 만들어보기</button>
                    </div>

                </div>
            </div>
        </div>
        <div class="footer">
            <img src="./../static/img/LIKELION%20UNIV_brandlogo_white_forweb_221111.png"/>
        </div>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/logout.js' %}"></script>
</html>