8주차세미나/Account/urls.py
from django.urls import path
from . import views as views
from django.contrib.auth.views import LogoutView

app_name = "account"

urlpatterns = [
    path("user/create/",views.UserCreate.as_view(), name = "signup"),
    path("user/login/",views.UserLoginView.as_view(),name = "login"),
    path("user/logout/",views.LogoutView.as_view(),name = "logout"),
    path("user/retrieve/",views.UserDetailView.as_view(),name = "user_detail"),
    path("user/update/",views.UserUpdateView.as_view()),
    path("user/delete/",views.UserDeleteView.as_view()),

]

8주차세미나/Post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path('create/', views.PostCreate.as_view(),name = "create"),
    path('list/cbv/', views.PostListView.as_view(),name = "list"),
    path('list/', views.PostListApiView.as_view(),name = "list_api"),
    path('detail/<int:pk>/cbv', views.PostDetailView.as_view(),name = "detail"),
    path('detail/<int:pk>/', views.PostDetailApiView.as_view(),name = "detail_api"),
    path('update/<int:pk>/', views.PostUpdateView.as_view(),name = "update"),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(),name = "delete"),

]

8주차세미나/Singlepage/urls.py
from django.urls import path
from . import views as views

app_name = "single_page"

urlpatterns = [
    path("",views.indexTemplateView.as_view(),name = "main"),
]

8주차세미나/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/",include("Account.urls")),
    path("",include("Singlepage.urls")),
    path("post/",include("Post.urls")),
    path("comment/",include("Comment.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

8주차세미나/Comment/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    content = models.CharField(max_length=200)
    author = models.ForeignKey("Account.User",on_delete=models.CASCADE)
    Post = models.ForeignKey("Post.Post",on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

8주차세미나/Post/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=100)

class Category(models.Model):
    name = models.CharField(max_length=100)

class Post(models.Model):
    title = models.CharField(max_length = 100)
    author = models.ForeignKey("Account.User",on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to="Post",blank = True, null = True)
    tag = models.ForeignKey(Tag,on_delete=models.CASCADE,null = True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)

8주차세미나/Post/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post
from .utils import Post_to_Json, PostList_to_Json

class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = ["title","content","image"]
    template_name = "newPost.html"
    login_url = '/account/user/login/'
    redirect_field_name = 'redirect_to'
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            messages.error(self.request, '로그인을 먼저 해주세요.', extra_tags='danger')
            return redirect("account:login")

    def form_invalid(self, form):
        print(form.data,form.errors)
        return super(PostCreate, self).form_invalid(form)

    def get_success_url(self):
        return reverse("post:list")

class PostListView(ListView):
    model = Post
    paginate_by = 10
    template_name = "post.html"

class PostListApiView(View):
    def get(self, request, *args, **kwards):
        data = Post.objects.all()
        data = PostList_to_Json(data)
        context = {
            "posts" : data
        }
        return JsonResponse(context)

class PostDetailView(DetailView):
    model = Post
    template_name = "postDetail.html"

class PostDetailApiView(View):
    def get(self, request, *args, **kwards):
        print(kwards)
        data = Post.objects.get(id = kwards["pk"])
        data = Post_to_Json(data)
        context = {
            "post" : data
        }
        return JsonResponse(context)
class PostUpdateView(UpdateView):
    model = Post
    fields = ["title","content","image"]
    template_name = "editPost.html"

    def form_valid(self, form):
        obj = self.get_object()
        current_user = self.request.user
        if current_user.is_authenticated and current_user == obj.author:
            form.instance.author = current_user
            form.instance.image = obj.image
            return super(PostUpdateView, self).form_valid(form)
        else:
            messages.error(self.request, '로그인을 먼저 해주세요.', extra_tags='danger')
            return redirect("account:login")

    def form_invalid(self, form):
        obj = self.get_object()
        print(1)
        if form.instance.image=="":
            form.instance.image = obj.image
            return super(PostUpdateView, self).form_valid(form)
        else:
            print(form.data,form.errors)
            return super(PostUpdateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse("post:detail",args=(str(self.get_object().pk)))

class PostDeleteView(DeleteView):
    model = Post

    success_url = reverse_lazy("post:list")
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return JsonResponse({"status":True})

    # def get(self, request, *args, **kwargs):
    #     return self.delete(request, *args, **kwargs)

8주차세미나/Post/templates/editPost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>게시글 수정하기</title>
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="post_body_wrap">
  <div class="main_menu">
    <h2 onClick="location.href='/'">BLOG CRUD 연습하기</h2>
    <div class="main_right_menu">
      {% if user.is_authenticated %}
          <p class="userName">환영합니다 {{user.get_full_name}}님</p>
          <button type="button" class="logoutBt" onclick="logout();">로그아웃</button>
      {% else %}
          <p onclick="location.href='{% url 'account:login' %}'">로그인</p>
          <p onclick="location.href='{% url 'account:signup' %}'">회원가입</p>
      {% endif %}
    </div>
  </div>
  <form action = "/post/update/{{post.id}}/" method = "post">
    {% csrf_token %}
  <div class="post_body">
    <div class="post_detail_wrap">
      <div class="post_detail_title">
        <input type="text" id="postTitle" name = "title" value = "{{form.instance.title}}" />
      </div>
      <div class="post_detail_content2">
        {{form.instance.content}}
        <textarea id="postContent" name = "content" >{{form.instance.content}}</textarea>
      </div>
    </div>
  </div>
    <input id = "form_submit" type = "submit" style = "display:none">
    </form>
  <div class="post_bt_wrap">
    <button type="button" onclick="completePost_cbv();">
      저장하기
    </button>
  </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/editPost.js' %}"></script>
<script src="{% static 'js/logout.js' %}"></script>
</html>

8주차세미나/Post/templates/newPost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>게시글 수정하기</title>
<link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
    <div class="post_body_wrap">
        <div class="main_menu">
            <h2 onClick="location.href='./index.html'">BLOG CRUD 연습하기</h2>
            <div class="main_right_menu">
                {% if user.is_authenticated %}
                    <p class="userName">환영합니다 {{user.get_full_name}}님</p>
                    <button type="button" class="logoutBt" onclick="logout();">로그아웃</button>
                {% else %}
                    <p onclick="location.href='{% url 'account:login' %}'">로그인</p>
                    <p onclick="location.href='{% url 'account:signup' %}'">회원가입</p>
                {% endif %}
            </div>
        </div>
        <div class="post_body">
            <form action = "{% url 'post:create' %}" method = "post">
                {% csrf_token %}
                <div class="post_detail_wrap">
                    <div class="post_detail_title">
                        <input type="text" id="postTitle" name = "title" placeholder="제목을 입력해주세요."/>
                    </div>
                    <div class="post_detail_content">
                        <textarea id="postContent" name = "content" placeholder="내용을 입력해주세요."></textarea>
                    </div>
                </div>
                <div class="post_bt_wrap">
                    <button type="button" onclick="completeNewPost_cbv();">
                        저장하기
                    </button>
                    <input id = "form_submit" type = "submit" style = "display:none">
                </div>
            </form>
        </div>
    </div>
    </body>

    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'js/newPost.js' %}"></script>
<script src="{% static 'js/logout.js' %}"></script>
</html>ㄴ

8주차세미나/Post/templates/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시판 목록</title>
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="post_body_wrap">
    <div class="main_menu">
      <h2 onClick="location.href='{% url 'single_page:main' %}'">BLOG CRUD 연습하기</h2>
      <div class="main_right_menu">
          {% if user.is_authenticated %}
            <p class="userName">환영합니다 {{user.get_full_name}}님</p>
            <button type="button" class="logoutBt" onclick="logout();">로그아웃</button>
          {% else %}
            <p onclick="location.href='{% url 'account:login' %}'">로그인</p>
            <p onclick="location.href='{% url 'account:signup' %}'">회원가입</p>

          {% endif %}
      </div>
    </div>
    <div class="post_body2">
      <div class="post_list_wrap" id="postListWrap">
<!--        <div class='post_list' onClick='moveDetailPost(" + data.posts[i].id + ");'>-->
<!--          <div class='post_title'><h3>" + data.posts[i].title + "</h3></div>-->
<!--          <div class='post_time'><h3>" + data.posts[i].updated_at + "</h3></div>-->
<!--        </div>-->
      </div>
      <div class="post_bt_wrap">
          <button type="button" onclick="movePost();">
              작성하기
          </button>
      </div>
    </div>
  </div>
</body>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/post.js' %}"></script>
<script src="{% static 'js/logout.js' %}"></script>
</html>

8주차세미나/Post/templates/postDetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>게시판 목록</title>
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="post_body_wrap">
  <div class="main_menu">
    <h2 onClick="location.href='/'">BLOG CRUD 연습하기</h2>
    <div class="main_right_menu">
      {% if user.is_authenticated %}s
            <p class="userName">환영합니다 {{user.get_full_name}}님</p>
            <button type="button" class="logoutBt" onclick="logout();">로그아웃</button>
          {% else %}
            <p onclick="location.href='{% url 'account:login' %}'">로그인</p>
            <p onclick="location.href='{% url 'account:signup' %}'">회원가입</p>

          {% endif %}
    </div>
  </div>
  <div class="post_body">
    <div class="post_detail_wrap">
      <div class="post_detail_title">
        <h1>{{post.title}}</h1>
      </div>
      <div class="post_detail_info">
        <p>{{post.author.get_full_name}}</p>
        <p>{{post.created_at|date:'Y-m-d H:i'}}</p>
      </div>
      <div class="post_detail_content">
        <p>{{post.content}}</p>
      </div>
    </div>
  </div>

  <div class="post_bt_wrap">
    {% if user.is_authenticated and user == post.author %}
    <button type="button" onclick="moveEditPost(id);">
      수정하기
    </button>
    <button type="button" onclick="deletePost(id);">
      삭제하기
    </button>
    {% endif %}
  </div>

  <div class="post_detail_comment_wrap">
    {% for comment in post.comment_set.all %}
      <div class="post_detail_comment_box">
        <div>
          <p id="userName">{{comment.author.get_full_name}} ({{comment.created_at|date:'Y-m-d H:i'}})</p>
          <p id="userComment">{{comment.content}}</p>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="post_detail_newComment_wrap">
    <div class="post_detail_newComment_box">
      <input type="text" id="commentInput" placeholder="댓글을 입력하세요"/>
      <button type="button" onclick="createNewComment();">등록</button>
    </div>
  </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/postDetail.js' %}"></script>
<script src="{% static 'js/logout.js' %}"></script>
</html>